---
#
# Ansible managed
#
repository:
  description: Install and configure snort on your system.
  homepage: https://robertdebock.nl/
  topics: snort, server, system, ansible, molecule, tox, playbook, hacktoberfest
