---
sudo: required
language: python
services: docker

env:
  - version=">=2.6,<2.7" distro="alpine-latest" expectation="fail"
  - version="" distro="alpine-latest" expectation="fail"
  - version="devel" distro="alpine-latest" expectation="fail"
  - version=">=2.6,<2.7" distro="alpine-edge" expectation="fail"
  - version="" distro="alpine-edge" expectation="fail"
  - version="devel" distro="alpine-edge" expectation="fail"
  - version=">=2.6,<2.7" distro="archlinux" expectation="fail"
  - version="" distro="archlinux" expectation="fail"
  - version="devel" distro="archlinux" expectation="fail"
  - version=">=2.6,<2.7" distro="centos-6" expectation="fail"
  - version="" distro="centos-6" expectation="fail"
  - version="devel" distro="centos-6" expectation="fail"
  - version=">=2.6,<2.7" distro="centos-latest"
  - version="" distro="centos-latest"
  - version="devel" distro="centos-latest"
  - version=">=2.6,<2.7" distro="debian-latest" expectation="fail"
  - version="" distro="debian-latest" expectation="fail"
  - version="devel" distro="debian-latest" expectation="fail"
  - version=">=2.6,<2.7" distro="debian-stable" expectation="fail"
  - version="" distro="debian-stable" expectation="fail"
  - version="devel" distro="debian-stable" expectation="fail"
  - version=">=2.6,<2.7" distro="debian-unstable" expectation="fail"
  - version="" distro="debian-unstable" expectation="fail"
  - version="devel" distro="debian-unstable" expectation="fail"
  - version=">=2.6,<2.7" distro="fedora-latest"
  - version="" distro="fedora-latest"
  - version="devel" distro="fedora-latest"
  - version=">=2.6,<2.7" distro="fedora-rawhide"
  - version="" distro="fedora-rawhide"
  - version="devel" distro="fedora-rawhide"
  - version=">=2.6,<2.7" distro="opensuse-leap" expectation="fail"
  - version="" distro="opensuse-leap" expectation="fail"
  - version="devel" distro="opensuse-leap" expectation="fail"
  - version=">=2.6,<2.7" distro="ubuntu-rolling" expectation="fail"
  - version="" distro="ubuntu-rolling" expectation="fail"
  - version="devel" distro="ubuntu-rolling" expectation="fail"
  - version=">=2.6,<2.7" distro="ubuntu-latest" expectation="fail"
  - version="" distro="ubuntu-latest" expectation="fail"
  - version="devel" distro="ubuntu-latest" expectation="fail"
  - version=">=2.6,<2.7" distro="ubuntu-devel" expectation="fail"
  - version="" distro="ubuntu-devel" expectation="fail"
  - version="devel" distro="ubuntu-devel" expectation="fail"

matrix:
  allow_failures:
    - env: version=">=2.6,<2.7" distro="alpine-edge" expectation="fail"
    - env: version="" distro="alpine-edge" expectation="fail"
    - env: version="devel" distro="alpine-edge" expectation="fail"
    - env: version="devel" distro="alpine-latest" expectation="fail"
    - env: version="devel" distro="archlinux" expectation="fail"
    - env: version="devel" distro="centos-6" expectation="fail"
    - env: version="devel" distro="centos-latest"
    - env: version="devel" distro="debian-latest" expectation="fail"
    - env: version="devel" distro="debian-stable" expectation="fail"
    - env: version=">=2.6,<2.7" distro="debian-unstable" expectation="fail"
    - env: version="" distro="debian-unstable" expectation="fail"
    - env: version="devel" distro="debian-unstable" expectation="fail"
    - env: version="devel" distro="fedora-latest"
    - env: version=">=2.6,<2.7" distro="fedora-rawhide"
    - env: version="" distro="fedora-rawhide"
    - env: version="devel" distro="fedora-rawhide"
    - env: version="devel" distro="opensuse-leap" expectation="fail"
    - env: version="devel" distro="ubuntu-rolling" expectation="fail"
    - env: version=">=2.6,<2.7" distro="ubuntu-devel" expectation="fail"
    - env: version="" distro="ubuntu-devel" expectation="fail"
    - env: version="devel" distro="ubuntu-devel" expectation="fail"
    - env: version="devel" distro="ubuntu-latest" expectation="fail"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${version}" != "devel" ] ; then pip install ansible"${version}" ; fi
  - if [ "${version}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "kFzleq1t8j5wfwbsCdZ34zrrbEBmJH/U4RP6o/owFvO4rVugNGbAdW+sdm3bwcl0wcTYSesyobUJyilQfIINyr2LV194i/8TAMskasN6/k8e9ELXPeCW6TDpntVFg+hhLADFVh/aXXNXdHF5a1nkhRXnNk0QNi3gFyHBR+pJksB+N9zvYNf5D4hQ5b9bzQeCU3+QjjkHMgK8LmtF89JxL3+ipEdu9eVl+w+P087TQqGx0RDpMFQrr7jBoxws/Bsgu2lfdgsWnLbUBbmacN6XwihFyKKTHBfjs4LvlD4TFLBFinvYhIUGhtSyTu7ZF80GwZUhgdbCFrpyhsOS58LOr5AA/3oZG9corekjei52KJekC1kYWclmX5XyMaoIwKYL3b02EB1dhSE6yX32qCUThWt0M3GMsu+42YyAzxVZWA3AT2NtT5BMgAH3FovJmW9urBuWrbXwjrnwsfubp5gWQ8JtevDycG5QExFGeiT2ELCBYFFCkbU7yLqr3nqJvv66QdNfsqr0oBRR1F+PSs9wcv9uu2V6J4X1xJ5ckWu8ZNuk5RDa72olFWgYKWKoqZwGWyAqJ77bnkB22+hPas75iCQIDCUbnAKaSb75WePvblEk6ACp+xLvsmatFd1wFqULk/494Z//OpRmPstjg5Kjr0+J6gkjaI9YGb2CH22EM+U="
  email: false
