---
# tasks file for snort
- name: install requirements
  package:
    name: "{{ snort_requirements }}"
    state: present
  register: snort_install_requirements
  until: snort_install_requirements is succeeded
  retries: 3

- name: unarchive software daq
  unarchive:
    src: "{{ snort_archive_daq }}"
    dest: "{{ snort_unarchive_directory }}"
    validate_certs: "{{ snort_validate_certs }}"
    remote_src: yes
    creates: "{{ snort_unarchive_directory }}/daq-{{ snort_daq_version }}"
  notify:
    - configure daq
    - make daq
    - make install daq

- name: flush handlers
  meta: flush_handlers

- name: unarchive software snort
  unarchive:
    src: "{{ snort_archive }}"
    dest: "{{ snort_unarchive_directory }}"
    validate_certs: "{{ snort_validate_certs }}"
    remote_src: yes
    creates: "{{ snort_unarchive_directory }}/snort-{{ snort_version }}"
  register: unarchive_software
  until: unarchive_software is succeeded
  retries: 3
  notify:
    - configure
    - make
    - make install

- name: flush handlers
  meta: flush_handlers

- name: ensure rules directory exists
  file:
    path: /etc/snort/rules
    state: directory

- name: install community rules
  unarchive:
    src: "{{ item }}"
    dest: /etc/snort/rules
    validate_certs: "{{ snort_validate_certs }}"
    remote_src: yes
  loop:
    - "https://www.snort.org/downloads/community/opensource.gz"
    - "https://www.snort.org/downloads/community/snort3-community-rules.tar.gz"
    - "https://snort.org/downloads/community/community-rules.tar.gz"
  register: snort_install_community_rules
  until: snort_install_community_rules is succeeded
  retries: 3

- name: create service
  import_role:
    name: robertdebock.service
  vars:
    service_list:
      - name: "{{ snort_service }}"
        description: Snort NIDS Daemon
        start_command: /usr/local/bin/snort -q -i {{ ansible_default_ipv4.interface }}

- name: start and enable software
  service:
    name: "{{ snort_service }}"
    state: started
    enabled: yes
