---
# tasks file for snort
- name: install required software
  package:
    name: "{{ snort_required_software }}"
    state: "{{ snort_package_state }}"
  register: snort_install_required_software
  until: snort_install_required_software
  retries: 3

- name: create a symbolic link libdnet.1
  file:
    src: /usr/lib64/libdnet.so.1.0.1
    dest: /usr/lib64/libdnet.1
    state: link

- name: install software
  package:
    name: "{{ snort_packages }}"
    state: "{{ snort_package_state }}"
  register: snort_install_softwrae
  until: snort_install_softwrae
  retries: 3

- name: install community rules
  unarchive:
    src: https://snort.org/downloads/community/community-rules.tar.gz
    dest: /etc/snort/rules
    remote_src: yes

- name: start and enable software
  service:
    name: "{{ snort_service }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker" or snort_ignore_docker
