---
# tasks file for snort
- name: install requirements
  package:
    name: "{{ snort_requirements }}"
    state: present
  register: snort_install_requirements
  until: snort_install_requirements is succeeded
  retries: 3

- name: unarchive software daq
  unarchive:
    src: "{{ snort_archive_daq }}"
    dest: "{{ snort_unarchive_directory }}"
    remote_src: yes
    creates: "{{ snort_unarchive_directory }}/daq-{{ snort_daq_version }}"
  register: unarchive_software_daq
  until: unarchive_software_daq is succeeded
  retries: 3
  notify:
    - configure daq
    - make daq
    - make install daq

- name: flush handlers
  meta: flush_handlers

- name: unarchive software snort
  unarchive:
    src: "{{ snort_archive }}"
    dest: "{{ snort_unarchive_directory }}"
    remote_src: yes
    creates: "{{ snort_unarchive_directory }}/snort-{{ snort_version }}"
  register: unarchive_software
  until: unarchive_software is succeeded
  retries: 3
  notify:
    - configure
    - make
    - make install

- name: flush handlers
  meta: flush_handlers

- name: ensure rules directory exists
  file:
    path: /etc/snort/rules
    state: directory

- name: install community rules
  unarchive:
    src: https://snort.org/downloads/community/community-rules.tar.gz
    dest: /etc/snort/rules
    remote_src: yes

- name: start and enable software
  service:
    name: "{{ snort_service }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
