---
# tasks file for snort
- name: install requirements
  package:
    name: "{{ snort_requirements }}"
    state: present
  register: snort_install_requirements
  until: snort_install_requirements is succeeded
  retries: 3

- name: install snort
  package:
    name: "{{ snort_package_url }}"
  register: snort_install_snort
  until: snort_install_snort is succeeded
  retries: 3

- name: link libdnet.1
  file:
    src: /usr/lib64/libdnet.so.1.0.1
    dest: /usr/lib64/libdnet.1
    state: link

- name: get rules
  unarchive:
    src: "{{ item.url }}"
    dest: /etc/snort/rules
    remote_src: yes
  loop: "{{ snort_community_rules }}"
  loop_control:
    label: "{{ item.url }}"
  register: snort_get_community_rules
  until: snort_get_community_rules is succeeded
  retries: 3

- name: include rules
  lineinfile:
    path: /etc/snort/snort.conf
    line: "include $SO_RULES_PATH/{{ item.file }}"
  loop: "{{ snort_community_rules }}"
  loop_control:
    label: "{{ item.file }}"
  notify:
    - restart snort

- name: start and enable software
  service:
    name: "{{ snort_service }}"
    state: started
    enabled: yes
